export const GENRE_OPTIONS = [
  "Action",
  "Adventure",
  "Fantasy",
  "Thriller",
  "Mystery",
  "Sci-Fi",
  "Drama",
  "Comedy",
  "Horror",
  "Family",
  "Documentary",
  "Anime",
  "Romance",
  "Crime",
] as const;

export const GENRE_LABEL_ES: Record<string, string> = {
  Action: "Acción",
  Adventure: "Aventura",
  Fantasy: "Fantasía",
  Thriller: "Suspenso",
  Mystery: "Misterio",
  "Sci-Fi": "Ciencia ficción",
  Drama: "Drama",
  Comedy: "Comedia",
  Horror: "Terror",
  Family: "Familiar",
  Documentary: "Documentales",
  Anime: "Anime",
  Romance: "Romance",
  Crime: "Crimen",
};
